// AUTO-GENERATED by configure_xcode.rb - DO NOT EDIT MANUALLY
// This file is regenerated on each test run with discovered test files

#import "AppDelegate.h"
#import <unistd.h>
#include "graph/graph.h"

extern int test_engine_main();
extern int test_graph_main();
extern int test_index_main();
extern int test_kernel_main();
extern int test_kv_cache_main();
extern int test_performance_main();

@implementation AppDelegate

- (void)copyFromBundle:(NSString *)bundlePath toDocuments:(const char *)name {
    if (!name) return;
    NSFileManager *fileManager = [NSFileManager defaultManager];
    NSString *itemName = [NSString stringWithUTF8String:name];
    NSString *sourceItemPath = [NSString stringWithFormat:@"%@/%@", bundlePath, itemName];
    if (![fileManager fileExistsAtPath:sourceItemPath]) {
        fprintf(stderr, "[CactusTest] copyFromBundle: source not found: %s\n", [sourceItemPath UTF8String]);
        return;
    }
    if ([fileManager fileExistsAtPath:itemName]) {
        NSError *removeError = nil;
        [fileManager removeItemAtPath:itemName error:&removeError];
        if (removeError) {
            fprintf(stderr, "[CactusTest] copyFromBundle: failed to remove existing %s: %s\n",
                [itemName UTF8String], [[removeError localizedDescription] UTF8String]);
        }
    }
    NSError *copyError = nil;
    [fileManager copyItemAtPath:sourceItemPath toPath:itemName error:&copyError];
    if (copyError) {
        fprintf(stderr, "[CactusTest] copyFromBundle: failed to copy %s -> %s: %s\n",
            [sourceItemPath UTF8String], [itemName UTF8String], [[copyError localizedDescription] UTF8String]);
    } else {
        fprintf(stderr, "[CactusTest] copyFromBundle: copied %s -> %s\n",
            [sourceItemPath UTF8String], [itemName UTF8String]);
    }
}

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    NSArray *paths = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES);
    NSString *documentsDirectory = paths[0];
    chdir([documentsDirectory UTF8String]);

#if !TARGET_OS_SIMULATOR
    freopen("cactus_test.log", "w", stdout);
    freopen("cactus_test.log", "a", stderr);
    setbuf(stdout, NULL);
    setbuf(stderr, NULL);
#endif

    cactus::Logger::instance().set_level(cactus::LogLevel::DEBUG);

    NSString *bundlePath = [[NSBundle mainBundle] bundlePath];
    [self copyFromBundle:bundlePath toDocuments:getenv("CACTUS_TEST_MODEL")];
    [self copyFromBundle:bundlePath toDocuments:getenv("CACTUS_TEST_TRANSCRIBE_MODEL")];
    [self copyFromBundle:bundlePath toDocuments:getenv("CACTUS_TEST_VAD_MODEL")];
    [self copyFromBundle:bundlePath toDocuments:getenv("CACTUS_TEST_ASSETS")];

    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(NSEC_PER_SEC)), dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
        test_engine_main();
        test_graph_main();
        test_index_main();
        test_kernel_main();
        test_kv_cache_main();
        test_performance_main();
        exit(0);
    });

    return YES;
}

@end
